---
title: "CreateDecisionTree"
format: html
---

# 1. Create and save Decision Tree for selecting a modeling approach

```{r}
library(grid)
library(tidyverse)
library(patchwork)

rightadjust = 1

# Define node positions
nodes <- data.frame(
  id = 1:5,
  x = c(3, 4.5, 1.5, 0.0, 3)+rightadjust,
  y = c(6, 4, 4, 2, 2),
  label = c(
    "Do you know the\nshape of the\nhazard function?",
    "Parametric\nSurvival Models",
    "Do you care about\nthe shape of the\nhazard function?",
    "Cox\nRegression Model",
    "Discrete-Time Model\nor Piecewise\nExponential Model"
  ),
  type = c("question", "outcome", "question", "outcome", "outcome")
)


# Define edges
edges <- data.frame(
  from_x = c(3, 3, 1.5, 1.5)+rightadjust,
  from_y = c(5.4, 5.4, 3.4, 3.4),
  to_x = c(4.5, 1.5, 0, 3)+rightadjust,
  to_y = c(4.7, 4.7, 2.7, 2.7),
  label = c("Yes", "No", "No", "Yes"),
  label_x = c(3.8, 2.2, .7, 2.3)+rightadjust,
  label_y = c(5.1, 5.1, 3.1, 3.1)
)

# Create the plot
ggplot() +
  # Draw edges
  geom_segment(data = edges, 
               aes(x = from_x, y = from_y, xend = to_x, yend = to_y),
               arrow = arrow(length = unit(0.4, "cm"), type = "closed", angle = 15),
               linewidth = 1.2, color = "#2c3e50") +
  
  # Add edge labels
  geom_label(data = edges,
             aes(x = label_x, y = label_y, label = label),
             fill = "white", color = "#2c3e50", 
             fontface = "bold", size = 5, label.size = 0.5) +
  
  # Draw nodes
  geom_tile(data = nodes[nodes$type == "question", ],
            aes(x = x, y = y),
            width = 2, height = 1.2, 
            fill = "#3498db", color = "#2c3e50", size = 1.5) +
  
  geom_tile(data = nodes[nodes$type == "outcome", ],
            aes(x = x, y = y),
            width = 2, height = 1.2,
            fill = "#2ecc71", color = "#2c3e50", size = 1.5) +
  
  # Add node text
  geom_text(data = nodes,
            aes(x = x, y = y, label = label),
            color = "white", fontface = "bold", size = 5, lineheight = 0.9) +
  
  # Formatting
  coord_cartesian(xlim = c(0, 7), ylim = c(0.5, 7)) +
  theme_void() +
  theme(plot.margin = margin(0, 0, 0, 0),
        plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
        panel.background = element_rect(fill="white",color="white"),
        plot.background = element_rect(fill="white",color = "white")) +
  labs(title = "Event History Analysis Model Selection Decision Tree")
```

Save the tree.

```{r}
ggsave("REVIEW2/DecisionTreeMethods.png", width = 10, height = 10, dpi = 800, bg = "transparent")

```

# 2. Create a plot for normal distribution


```{r}



ntrials = 100000
mean = 350
sd = 60
bin_width = 20

rt_data = tibble(
  rt1 = rnorm(ntrials, mean, sd),
  rt2 = rexGAUS(ntrials,mu = 300, sigma = sd, nu = 100)
) %>%
  mutate(N = 1:n())

summary(rt_data$rt1)
summary(rt_data$rt2)

  
hist1 <- ggplot(rt_data, aes(x=rt1)) +
  geom_histogram(binwidth = bin_width, boundary = bin_width) +
  scale_x_continuous(limits = c(0,1200)) +
  theme_bw()
hist1

hist2 <- ggplot(rt_data, aes(x=rt2)) +
  geom_histogram(binwidth = bin_width, boundary = bin_width) +
  scale_x_continuous(limits = c(0,1200)) +
  theme_bw()
hist2





# extract bin boundaries and counts
dat1 <- layer_data(hist1)
head(dat1)
dim(dat1)
tail(dat1)


dat2 <- layer_data(hist2)
head(dat2)
dim(dat2)
tail(dat2)


# create life table
lt1 <- tibble(
  bin = 1:dim(dat1)[1],
  ncount = dat1$count,
  pmass = ncount/ntrials,
  cumul = cumsum(pmass),
  surv = 1 - cumul,
  haz = pmass/lag(surv, 1),
  endp = bin*bin_width,
  endpo = dat1$xmax
)
dim(lt1)

lt2 <- tibble(
  bin = 1:dim(dat2)[1],
  ncount = dat2$count,
  pmass = ncount/ntrials,
  cumul = cumsum(pmass),
  surv = 1 - cumul,
  haz = pmass/lag(surv, 1),
  endp = bin*bin_width,
  endpo = dat2$xmax
)
dim(lt2)

# check
tail(lt1,15)
head(lt1,15)

# replace Inf with Nan
#lt[sapply(lt, is.infinite)] <- NA

# reduce size
#lt <- lt %>% filter(bin < 37)

# replace NA with 0
lt1 <- lt1 %>% 
  mutate(haz = ifelse(bin == 1, 0, haz)) %>%
  mutate(haz = ifelse(ncount == 0 & cumul > .999999, NA, haz))
lt2 <- lt2 %>% 
  mutate(haz = ifelse(bin == 1, 0, haz)) %>%
  mutate(haz = ifelse(ncount == 0 & cumul > .999999, NA, haz))



# check
tail(lt1,15)
tail(lt1,15)
  
head(lt1)

p1 <- tibble(
  bin = lt1$bin,
  normal = lt1$haz,
  exgaussian = lt2$haz
) %>% 
  pivot_longer(cols = normal:exgaussian,
               values_to  = "hazard"
               ) %>%
  rename(distribution = name) %>%
  ggplot(aes(x=bin,y=hazard,group=distribution,colour=distribution)) +
  geom_line() + geom_point(size = .5) +
  theme_bw() +
  scale_y_continuous(limits = c(0,1), 
                     breaks = c(0,.25,.5,.75,1)) +
  scale_x_continuous(breaks = c(0,seq(2,60,4),60), 
                     limits = c(-0.4,60.1), 
                     labels = c(0,seq(2,60,4)*20,1200),
                     expand = expansion(mult = c(0, 0))) +
  labs(x = "time bin (upper limit in ms)") +
  theme(axis.text.x = element_text(angle=90),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())
p1

p2 <- tibble(
  bin = lt1$bin,
  normal = lt1$pmass,
  exgaussian = lt2$pmass
) %>% 
  pivot_longer(cols = normal:exgaussian,
               values_to  = "probability mass"
               ) %>%
    rename(distribution = name) %>%
  ggplot(aes(x=bin,y=`probability mass`,group=distribution,colour=distribution)) +
  geom_line() + geom_point(size = .5) +
  theme_bw() +
  scale_y_continuous(limits = c(0,.2), 
                     breaks = c(0,.1,.2))+
  scale_x_continuous(breaks = seq(1,60,4), limits = c(1,60), labels = seq(1,60,4)*20) +
  labs(x = "time bin (upper limit in ms)") +
  theme(axis.text.x = element_text(angle=90))
p2

p3 <- tibble(
  bin = lt1$bin,
  normal = lt1$surv,
  exgaussian = lt2$surv
) %>% 
  pivot_longer(cols = normal:exgaussian,
               values_to  = "survival probability"
               ) %>%
    rename(distribution = name) %>%
  ggplot(aes(x=bin,y=`survival probability`,group=distribution,colour=distribution)) +
  geom_line() + geom_point(size = .5) +
  theme_bw() +
  scale_y_continuous(limits = c(0,1), 
                     breaks = c(0,.25,.5,.75,1))+
  scale_x_continuous(breaks = seq(1,60,4), limits = c(1,60), labels = seq(1,60,4)*20) +
  labs(x = "time bin (upper limit in ms)") +
  theme(axis.text.x = element_text(angle=90),
        panel.grid.minor.y = element_blank())
p3

p4 <- tibble(
  bin = lt1$bin,
  normal = lt1$cumul,
  exgaussian = lt2$cumul
) %>% 
  pivot_longer(cols = normal:exgaussian,
               values_to  = "cumulative probability"
               ) %>%
    rename(distribution = name) %>%
  ggplot(aes(x=bin,y=`cumulative probability`,group=distribution,colour=distribution)) +
  geom_line() + geom_point(size = .5) +
  theme_bw() +
  scale_y_continuous(limits = c(0,1), 
                     breaks = c(0,.25,.5,.75,1))+
  scale_x_continuous(breaks = seq(1,60,4), limits = c(1,60), labels = seq(1,60,4)*20) +
  labs(x = "time bin (upper limit in ms)") +
  theme(axis.text.x = element_text(angle=90),
        panel.grid.minor.y = element_blank())
p4
# plot functions
# p1 <- ggplot(lt, aes(x=rt,y=cumul)) +
#                geom_line() + geom_point() + theme_bw()+
#                scale_y_continuous(limits = c(-0.1,1.1), 
#                                   breaks = c(0,.25,.5,.75,1))
#              
# p2 <- ggplot(lt, aes(x=rt,y=pmass)) +
#                geom_line() + geom_point() + theme_bw()+
#                scale_y_continuous(limits = c(-0.1,.5), 
#                                   breaks = c(0,.25,.5))
# 
# p3 <- ggplot(lt, aes(x=rt,y=surv)) +
#                geom_line() + geom_point() + theme_bw()+
#                scale_y_continuous(limits = c(-0.1,1.1), 
#                                   breaks = c(0,.25,.5,.75,1))
# 
# p4 <- ggplot(lt, aes(x=rt,y=haz)) +
#                geom_line() + geom_point() + theme_bw() +
#                scale_y_continuous(limits = c(-0.1,1.1), 
#                                   breaks = c(0,.25,.5,.75,1))

             
p4_theme <- p4 + theme(legend.position = "none")
p2_theme <- p2 + theme(legend.position = "none")
p3_theme <- p3 + theme(legend.position = "none")

  (p2_theme / p4_theme / p3_theme / p1) +
#    plot_annotation(title = title) +
    plot_layout(guides = "collect",
                axes = "collect_x") & 
    theme(legend.position = "bottom")



```


Save the plot

```{r}
ggsave("REVIEW2/Plot_distributions.png", width = 10, height = 10, dpi = 800)

```









