---
title: "Review 2: Author responses"
author: "Panis & Ramsey"
date: "10.11.2025"
output: 
  pdf_document:
      keep_tex: true
header-includes:
  - \usepackage{framed}
  - \usepackage{xcolor}
  - \let\oldquote\quote
  - \let\endoldquote\endquote
  - \renewenvironment{quote}{\begin{leftbar}}{\end{leftbar}}
---

```{r setup, include=FALSE}
# By default, the code chunks are hidden for brevity. Set the echo argument to TRUE for blocks you want to share the code in the output for. 
knitr::opts_chunk$set(echo = F)
```

We appreciate the time taken by the editor and reviewers to provide further feedback, as your comments have enabled us to improve the manuscript. We document our responses to your comments below.

# Editor

>AMPPS - Decision on Manuscript ID AMPPS-24-0232.R1
Advances in Methods and Practices in Psychological Science
25-Sep-2025
Dear Dr. Panis:
Thank you for re-submitting your Tutorial (AMPPS-24-0232.R1) entitled "Event History Analysis for psychological time-to-event data: A tutorial in R with examples in Bayesian and frequentist workflows" to Advances in Methods and Practices in Psychological Science (AMPPS). I was fortunate to receive feedback from three of the original reviewers, and you will find their comments below this email and attached. As you will see, all three reviewers believe your paper is improved and that this work continues to have the potential to make a strong contribution. I continue to share this assessment, as well as the need for some further refinements. Therefore, I again invite you to revise and resubmit your manuscript for further consideration at AMPPS.
>All three reviewers acknowledge that the revised manuscript has improved in clarity, structure, and focus, with Reviewer 1 especially commending its sharper aims and increased utility for experimental psychologists working with response time data.

>That said, accessibility remains a shared concern. Reviewer 3 highlights that the tutorial is still challenging to follow, particularly for readers less familiar with event history analysis (EHA) or speed–accuracy tradeoff (SAT) approaches, and urges that key concepts and research design features be defined and explained in the main text rather than deferred to the supplement. 

Response: We appreciate that making this paper as accessible as possible is a key priority, given that one barrier to more use of event history analysis is the relative complexity of the approach compared to more conventional analyses.
As such, we have taken a lot of time and effort to first consider what kind of accessibility we are aiming to achieve, as well as how we might achieve it.
Our revised approach to making the paper accessible has several strands. 
First, consistent with our initial aims and instincts, we avoid presenting equations in the main text and instead provide them in supplementary materials. 
Although more mathematically-minded individuals may not appreciate this choice, they are not our primary target audience, in terms of widening access to these techniques. 
Moreover, the availability of supplementary materials means that we can make the main text accessible to a wider audience whilst not compromising on relevant details.
Second, in addition to relevant equations, we also make use of supplementary materials to expand on further background context whenever relevant.
Third, we have added a new glossary section, which defines and explains key terms and concepts.
Fourth, we have added a section (2.1.3) with relevant research questions.
Fifth, we refer to the CRAN Task View on survival analysis in section D of the Supplemental Material.
Overall, we feel these choices strike a nice balance in terms of accessibility. We do not want the paper to become overly long and technical, but we also want to provide a clear description of key terms, concepts and relevant equations.  

>Reviewer 2 raises several clarity-related concerns--particularly about the bin width discussion and about the interpretability of modeling decisions such as time window selection. 

Response: We include a new Supplementary Figure to illustrate the choice of bin width (Supplementary Figure 3), and better explain the selection of a time window for analysis (page 25; lines 470-473).

>Both Reviewers 2 and 3 emphasize the need to better motivate methodological choices, especially the use of discrete-time EHA, which is currently justified by lab familiarity rather than a clear articulation of its analytic tradeoffs (R3, citing p. 8 of the ms). 

Response: We now motivate the use of discrete-time EHA extensively. First, in section 2.1.2 (pages 9-11). Second, in section D of the Supplemental Material, where we provide a decision tree, and compare the shape of empirical and parametric distributions.

>Reviewer 3 also recommends that the paper more clearly identify the types of research questions EHA is particularly well-suited to address, ideally with earlier and more focused examples (R3, citing p. 10 of the ms). I agree with this point and feel it's critical to make the paper as accessible as possible-- perhaps with (and not limited to) easier examples up front, a glossary of sorts, visualizations; anything (and everything) that will make this complex paper more inviting. 

Response: We now include a glossary (section 5) and example research questions (section 2.1.3) in the main text of the revised ms.
Also, we added extra sections to the Supplemental Material, to increase the accessiblity further, such as a visual comparison between probability mass, survival, cumulative distribution, and hazard functions in discrete time.


>While the paper is technically strong and substantively valuable, its didactic function would be enhanced by more clearly integrating definitions, rationales, and analytic guidance into the main text for the broader AMPPS readership. I'd encourage you to go through the paper start-to-end with an eye toward improving all possible points of entry and overall accessibility.

Response: We tried to improve all possible points of entry, as well as overall accessibility, by integrating definitions, examples, rationales, and analytic guidance into the main text, and by providing a glossary of key terms.


>If you choose to submit a revision, please include a letter detailing your point-by-point responses to each reviewer comment and indicating how you changed the manuscript to address them. The revised manuscript may undergo further peer review. We ask that you submit your revision within three months. Please let us know if you will not be able to meet this deadline.
To submit your revision, log into http://mc.manuscriptcentral.com/ampps and enter your Author Center, where you will find your manuscript title listed under "Manuscripts with Decisions." Under "Actions," click on "Create a Revision." Your manuscript number has been appended to denote a revision.
IMPORTANT: Your original files are available to you when you upload your revised manuscript. Please delete any redundant or outdated files before completing the submission.
Once again, thank you for submitting your manuscript to AMPPS and I look forward to receiving your revision.

# Reviewer: 1

>Comments to the Author
>From my perspective, the authors have been extremely responsive to previous feedback. The manuscript has improved considerably. The manuscript now has a much clearer focus in terms of its aims (i.e., by targeting readers from experimental and cognitive psychology working with response time data), which greatly increases the utility of this work. The manuscript is also organized in a much more logical way, and it does a great job of referring to and contextualizing other helpful resources.
This work has the potential to make a major contribution to the field and it has been a pleasure to review this work.

Response: We thank Reviewer 1 for their positive comments.


# Reviewer 2

>Reviewer report for AMPPS-24-0232: “Event History Analysis for psychological time-to-
event data: A tutorial in R with examples in Bayesian and frequentist workflows”
Summary:
I appreciate the effort taken by the authors to strengthen the manuscript and find the
revised version much improved in terms of clarity and accessibility. In particular, the
introduction and motivation are much easier to follow. I believe this manuscript is a
useful contribution to the literature; however, I have a few remaining comments.

Response: We thank Reviewer 2 for their positive comments.

>Major comments:

>1. I appreciate the authors’ attempt to address previous comments on determining
the appropriate bin width (p. 12). The authors note that bin widths need not be
constant over time was quite useful. This new paragraph on bin width has been
added under the section “Implications for research design” and I wonder if it
would be more appropriately placed elsewhere. The text’s current location
implies that bin width should be determined when designing the experiment,
rather than during analysis. I worry that suggesting that bin width be determined
during the design of the experiment could suggest (misleadingly) to some
researchers that response times ought to be collected in discrete time, rather
than continuous time; doing so would limit researchers’ ability to consider
alternative bin widths later during analysis. I suggest renaming this section
“Implications for research design and analysis” and making it clear that response
time data still should be recorded in continuous time, if multiple bin widths are to
be considered later during analysis.

Response: We renamed this section to "Implications for research in experimental psychology", and make it clear that RT data is typically treated as 
continuous time-to-event data, and so that it becomes implicitly clear that various bin widths can be considered later during analysis.
Furthermore, in the Supplemental Material we mention explicitly in section B that the continous-time RT data are interval censored.


>2. Related to the above comment on bin width, I also think some discussion of the
sensitivity of results and conclusions to the choice of bin width is both necessary
and useful, given that this is a tutorial paper and choosing the width of the bin is
a key step in modeling. The authors state generally that the “goal is to find the
smallest bin width that is supported by the amount of data available”
. This
guidance may be difficult to translate to actionable steps, particularly by a
researcher who is new to EHA. For example, what sort of metric is used to
determine “support”? Is it noise in the estimated hazard function or another
criterion? More specificity here could be useful, and I would recommend
including a supplementary example that illustrates both choosing a bin width and
any potential impact of that bin width on the conclusions.

Response: We include Supplementary Figure 3 to illustrate how results are sensitive to the choice of bin width. We also mention that "Overly small bin widths will result in erraticly shaped hazard functions, and some bins will have no events and thus hazard estimates of zero; overly large bin widths will result in a too great loss of temporal information (see Supplementary Figure 3)", on page 14 of the revised ms (lines 302-304).

>3. Figure 2: In the plot of ca(t), why is there a gap between the first and second
orange triangles? That is, why is ca(t) missing at 160ms?

Response: Because no responses were emitted in that time bin, so hazard equals 0 and ca(t) is undefined.

>4. P. 23 line 407-409: The text states, “First, because the first few bins often
contain no responses, one has to select an analysis time window, i.e., a
contiguous set of bins for which there is data for each participant.
” What is
meant here by “there is data for each participant”? And why is it important that
the first few bins often contain no responses—isn’t a lack of response at early
time points useful data? This sentence could benefit from being re-written for
increased clarity.

Response: We re-wrote this sentence (page 25; lines 468-471): "First, because the first few bins often contain no responses in RT tasks, one may want to select a smaller time window for analysis compared to the follow-up period in each trial (see section A of the Supplemental Material)"

>5. P. 38 line 641-643: “We might pick a hazard ratio…[that] is much smaller than
that previously observed”
. Do you mean closer to 1, i.e., weaker than previously
observed?

Response: Yes, we mean closer to 1 and thus a hazard ration that is weaker than previously observed. 


>Minor comments:
1. P. 26 line 446: “bernoulli” should be “Bernoulli”

Response: We changed this.


>2. P. 27 line 486: I would add the section reference numbers (section 4.6.4) for Kurz 2023a (either to the main text or to the reference list) to help interested readers find the relevant information.

Response: We added the section reference numbers in the main text.

>3. P. 27 line 489: If you first round a number to ‘digits = 1’ and then format using
‘nsmall = 2’, you may get a misleading value of 0 (i.e., 0.009 would appear as
0.00, when in fact 0.01 is more correct). This should be corrected.

Response: We corrected this.

>4. P. 32 line 558: “R package lme4()” should be “R package lme4”
, otherwise the
reference appears to be for a function, rather than an R package. Same
comment for “faux{}”—“faux” would be clearer.

Response: We followed both suggestions.


# Reviewer 3

>Comments to the Author
>This tutorial provides guidance on wrangling cognitive reaction time data and addressing questions about temporal dynamics of cognition using event history analysis (EHA) and speed/accuracy tradeoff (SAT) analysis, with illustrations of hazard and conditional accuracy functions. The manuscript is improved in some respects (e.g., shortening the text by moving the frequentist analyses to the supplement). 

Response: We thank Reviewer 3 for their supportive comments.


>At the same time, the tutorial remains challenging to follow, particularly for readers less familiar with EHA and SAT. To enhance accessibility, I encourage the authors to ensure that key information such as descriptions of research questions, RT data, and analytic approaches (including equations) is presented in the main text rather than moved to supplemental materials. This could likely be achieved without increasing the word count by reducing redundancies and tightening language in several places. Overall, the tutorial covers important concepts, but there is still room to strengthen its contributions, accessibility, and clarity.

Response: As we make clear in our response to the editor, we spent a long time considering how to make the paper as accessible as possible, whilst not compromising on clear descriptions of relevant detail. Please see the response to the editor for a summary of our revised approach. 
We now present the descriptions of RT data, research questions, and analytic approaches in the main text.
Nevertheless, we still opted to keep the text equation-light, to increase accessibility for non-mathematical psychologists.
We also added various new sections to the Supplemental Material and we added a glossary of key terms.
Together, we believe that these steps improve accessibility whilst also providing relevant depth where necessary.

>Contribution of this tutorial:
Thank you for clarifying the aims of the paper (line 89). To strengthen this section, it would be helpful to provide more rationale on the unique characteristics of RT data that necessitate a dedicated EHA tutorial. In particular, please address directly why a tutorial focused on RT data is needed. At present, key RT data characteristics (including the definition of “trial”) appear only in the supplement. Given the centrality of these features, I recommend moving them into the main text so the tutorial stands on its own.

Response: We followed this suggestion, and explain key RT characteristics in the main text now.

>The discussion at line 93 would benefit from greater emphasis on why a researcher might conduct EHA analyses. More clearly outlining the types of research questions that survival analysis of RT data can address would make the tutorial more useful and accessible. While some research questions are introduced later (pg. 10), I recommend stating them more clearly and incorporating them earlier (e.g., in Section 2.1).

Response: We now state research questions more clearly in section 2.1.3.


>In addition, the response to my previous comment that research questions were not expanded because they are “highly dependent on the field of study” seems at odds with the stated goal of offering a tutorial specific to RT data. Providing a focused set of examples would help balance breadth with depth and strengthen the tutorial’s clarity and relevance.

Response: We provide research questions in section 2.1.3.

>Use of discrete-time EHA:
Pg. 8 – The rationale given (“as a lab, and mainly for practical reasons, we have much more experience using discrete-time EHA”) is not a compelling justification for the analytic choice and feels out of place in a manuscript. One option to consider is to revise this paragraph to instead (1) clarify the distinction between discrete- and continuous-time approaches, (2) note that there are no strict cutoffs for when data should be treated as discrete versus continuous, and (3) highlight the relative advantages, limitations, or tradeoffs of each. This framing would be more informative for readers and align better with the tutorial’s didactic purpose.

Response: We revised this paragraph to clearly motivate our choice for discrete-time EHA (section 2.1.2; pages 9-11) and note that "there are no strict cutoffs for when data should be treated as discrete versus continuous". Also, in section D of the Supplemental Material, we provide a decision tree and compare the shape of empirical and parametric distributions.


>Clarity and accuracy:
Pg. 3 – The speed/accuracy tradeoff analysis is mentioned without explanation. Even if this concept is familiar to many experimental psychologists (as noted in your prior responses), it would strengthen the manuscript to include one or two sentences defining key terms or analysis types when first introduced. This would improve accessibility for a broader readership and support the tutorial’s clarity. I highlight a few examples below, but this should be considered throughout.

Response: We explain SAT analysis in the new Glossary (section 5).

>Pg. 8 – The phrase “discrete or continuous time units” is introduced without explanation. Please add a brief description of the distinction between these two approaches.

Response: We now mention on page 8:
"In RT tasks,response times are typically measured with a temporal resolution of 1 millisecond, or
higher. As 1 ms is typically short compared to the range of empirical RT distributions
(e.g., a half second), response times are generally treated as continuous time-to-event data."

And on page 9: "The type of models employed, and the definition of
hazard, depend on whether one is using continuous or discrete time units. Even though RT
is typically treated as a continuous variable, here we focus on discrete-time methods that
can be applied after grouping RTs into time periods (i.e., time intervals or time bins)."

Together with the information in sections B and D of the Supplemental Material, the distinction between these two approaches should be clear now.


>Pgs. 8-10 – Terms such as “hazard of response” (pg. 8) and “discrete-time hazard function” (pg. 9) are introduced without definition. 

Response: We introduce definitions for these terms in a new Glossary.


>Likewise, Figure 1 presents hazard and conditional accuracy equations but does not walk readers through their meaning or interpretation. I encourage you to keep the equations in the main text and provide accessible explanations, as this will better equip readers who may be less comfortable with mathematical notation. 

Response: We decided to remove the equations for hazard and conditional accuracy from the figure (to keep the text equation-light and accessible) and now provide accessible explanations in the figure legend, main text, and in the new glossary.


>Similarly it would be helpful to provide key definitions of “hazard” and “conditional accuracy estimates” should also be provided up front, rather than deferred to Section 2.1.2.

Response: We provide definitions in the new Glossary.

>Pg 9 – in discrete time, there is not instantaneous risk. Please revise.

Response: We removed "instantaneous" when talking about risk in discrete-time.

>Pg 14 – The manuscript would be strengthened if key EHA elements were defined directly in the main text rather than directing readers to the supplemental material.

Response: We define key EHA elements in the main text, and in the new Glossary.

>Pg 15 – In my original review I requested that right and left censoring be more clearly defined. Right censoring is still referred to several times in the manuscript without initial explanation of what this is. For the benefit of novice readers (since this is an AMPPS tutorial), I recommend including these definitions in the main text rather than the supplement.

Response: We include definitions for right- and left-censoring in the new Glossary.






