---
title: "tutorial_notes"
author: "Rich"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file is a way to provide feedback on draft versions of the tutorials. 
I can edit the tutorials directly of course (which git should track), but this is a space to provide comments.

# October 31st 2024 #

The basic workflow of the tutorials seems pretty good to me.
I can do some more fine-tuning of the code after the next revision of the manuscript,
given that some stuff will change.

## table of contents, aesthetics and apperance ##

I think we can easily improve the visual appearance of the tutorials in .html format by using a theme,
as well as their ease of navigation by setting a table of contents function.
To do so, include the following in th YAML header.

output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    theme: united

This is what we did in Andrew Wildman's psychopy tutorial. 
There are other themes, but this works for me.

-> Done.

# December 4th 2024 #

I took a look at tutorial2a.

## overall comments on structure ##

My feeling is that it is comprehensive and clear. Nice work on the prior predictive checks.

However, it is long. And there is a lot of additional material, which extends beyond what is required.
This is just an observation, and not necessarily a criticism.

To give you a few examples, the sidenote about prior predictive checks is long. And you calculate things twice in several places e.g., from draws manually and using convenience functions. Now, this might all add to the richness and depth of understanding that the tutorial provides. But, at the same time, it does appear to be going against our stated aim of removing barriers to entry. If we consider a more minimal structure, we would supply code in the tutorial to get the job done and nothing more. Readers would be able to walk along with the most direct and straightforward link to the main text. There could be a case that we are not showing enough skill in selecting what is most important.

Now, at the moment, I'm conflicted. The richness and context plus thinking and logic is good. But it makes it long with loads of plots. My worry is that someone reads the manuscript, flips to the tutorial and then thinks "oh boy, what's all this?" and then gives up.

For now, I say we leave it, but just keep it in mind for future revisions and accessibility, as it may need re-thinking later.

-> I moved the prior predictive checks to their own section at the end of tutorial 2a.

## epred draws ##

These look good in general. 
But let's have a quick discussion about one of them. Something came up when I was playing around.
I need to run it by you.


# December 5th 2024 #

I took a look at tutorial2b.

## coding conventions ##

I edited stuff to make each code argument after a pipe a new line. 
I think it is easier to read this way.
You can also "re-indent" lines to make the code more consistent in terms of indents also.
e.g., cmd+I or select the tab "code" then "re-indent lines"

-> great.

## priors ##

line 101. we don't say anything about how we came to set the priors how we did. 
Should we say something? Or do we say it elsewhere?
Maybe a few lines about weakly iformative priors and what that means in this context?

->  todo...

## plots ##

a very minor point.
for the grand average marginal effects, you facet by condition.
for the single subject marginal effects, you overlap the lines.
This is not a big deal, I'm just pointing out the difference.
e.g., you could plot the grand average in the same way. 
I'm not saying that would be better. I'm just saying that it would then be consistent.
It makes no difference overall as they are both very clear as they are.


